/** @type {import('tailwindcss').Config} */
export default {
	content: ['./**/*.html'],
	safelist: [
		'text-red_border',
		'text-blue_border',
		'text-green_border',
		'text-gray_border',
		'text-purple_border',
		'text-pink_border',
		'text-yellow_border',
		'hover:bg-red_500',
		'hover:bg-blue_500',
		'hover:bg-green_500',
		'hover:bg-gray_500',
		'hover:bg-purple_500',
		'hover:bg-pink_500',
		'hover:bg-yellow_500',
		'hover:bg-blue_light',
		'hover:bg-red_light',
		'hover:bg-green_light',
		'hover:bg-gray_light',
		'hover:bg-purple_light',
		'hover:bg-pink_light',
		'hover:bg-yellow_light',
		'aria-selected:bg-blue_500[aria-selected="true"]',
		'aria-selected:bg-red_500[aria-selected="true"]',
		'aria-selected:bg-green_500[aria-selected="true"]',
		'aria-selected:bg-gray_500[aria-selected="true"]',
		'aria-selected:bg-purple_500[aria-selected="true"]',
		'aria-selected:bg-pink_500[aria-selected="true"]',
		'aria-selected:bg-yellow_500[aria-selected="true"]',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-red_500',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-green_500',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-gray_500',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-blue_500',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-purple_500',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-pink_500',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-yellow_500',
		'text-blue_500',
		'text-red_500',
		'text-green_500',
		'text-gray_500',
		'text-purple_500',
		'text-pink_500',
		'text-yellow_500',
		'checked:bg-blue_500',
		'checked:bg-red_500',
		'checked:bg-gray_500',
		'checked:bg-green_500',
		'checked:bg-purple_500',
		'checked:bg-pink_500',
		'checked:bg-yellow_500',
		'hover:bg-blue_light',
		'hover:bg-red_light',
		'hover:bg-green_light',
		'hover:bg-gray_light',
		'hover:bg-purple_light',
		'hover:bg-pink_light',
		'hover:bg-yellow_light',
		'hover:text-blue_border',
		'hover:text-red_border',
		'hover:text-green_border',
		'hover:text-gray_border',
		'hover:text-purple_border',
		'hover:text-pink_border',
		'hover:text-yellow_border',
		'group:hover .group-hover:text-blue_500',
		'group:hover .group-hover:text-red_500',
		'group:hover .group-hover:text-green_500',
		'group:hover .group-hover:text-gray_500',
		'group:hover .group-hover:text-purple_500',
		'group:hover .group-hover:text-pink_500',
		'group:hover .group-hover:text-yellow_500',
		'group/slider__item:hover .group-hover/slider__item:shadow-blue_light/20',
		'group/slider__item:hover .group-hover/slider__item:shadow-red_light/20',
		'group/slider__item:hover .group-hover/slider__item:shadow-green_light/20',
		'group/slider__item:hover .group-hover/slider__item:shadow-gray_light/20',
		'group/slider__item:hover .group-hover/slider__item:shadow-purple_light/20',
		'group/slider__item:hover .group-hover/slider__item:shadow-pink_light/20',
		'group/slider__item:hover .group-hover/slider__item:shadow-yellow_light/20',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-blue_500',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-red_500',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-green_500',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-gray_500',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-purple_500',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-pink_500',
		'group/heading[aria-expanded="true"] .group-aria-expanded/heading:bg-yellow_500',
		
		
	],
	theme: {
		extend: {
			fontFamily: {
				SFUIText: ['SF UI Text', 'sans-serif'],
				display: ['SF UI Display', 'sans-serif'],
			},
		},
		lineHeight: {
			tight: '1.2',
		},
		boxShadow: {
			inset: 'inset 0 4px 10px 0 rgba(255, 255, 255, 0.1)',
			inner: '0 4px 10px 0 rgba(255, 255, 255, 0.5)',
			lg: '0 4px 50px 0 ',
			slider_img: '0px 4px 4px 0px rgba(0, 0, 0, 0.25)',
		},
		letterSpacing: {
			wider: '.04em',
		},
		colors: {
			gray_500: '#0b0b0c',
			gray_light: '#1e1e1e',
			gray_border: '#323232',
			txt: '#bdbdc0',
			white: '#fff',
			purple_500: '#7053ff',
			purple_light: '#7f65ff',
			purple_border: '#917aff',
			pink_500: '#ff2c60',
			pink_light: '#ff547e',
			pink_border: '#ff7194',
			blue_500: '#3f94ff',
			blue_border: '#72b0ff',
			blue_light: '#58a2ff',
			green_500: '#31b970',
			green_light: '#31b970',
			green_border: '#31b970',
			yellow_500: '#fbbf0d',
			yellow_light: '#ffca2e',
			yellow_border: '#ffd65e',
			red_500: '#f24822',
			red_light: '#fb6240',
			red_border: '#ff7050',
		},
		listStyleType: {
			none: 'none',
			disc: 'disc',
			decimal: 'decimal',
			square: 'square',
		},
		container: {
			center: true,
		},
	},
	plugins: [
		require('flowbite/plugin'),
		function ({ addComponents }) {
			addComponents({
				'.container': {
					maxWidth: '100%',
					'@screen sm': {
						maxWidth: '640px',
					},
					'@screen md': {
						maxWidth: '768px',
					},
					'@screen lg': {
						maxWidth: '1126px',
					},
					'@screen xl': {
						maxWidth: '1126px',
					},
				},
			})
		},
	],
}
